# A conda environment with all useful package for ctamclib developers
name: data-science
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - jupyter
  - ipython
  - scikit-learn
  - jupyterthemes
  - seaborn
  - conda-forge::jupyter_contrib_nbextensions
  
# cheatsheet
# create: conda env create -f environment.yml
# activate: conda activate gammasim-tools-dev
# update: conda env update -f environment.yml --prune
